Starting of the Documentation
lervag/vimtex pull request #1961
Opened 2021-02-16 09:45 UTC by TornaxO7

# Currently added

- Added Table of Contents in the CONTRIBUTE.md file
- Added new section: 'Documentation'
    => Added a little file structure

# Information
The documentation isn't finished yet! I'll tell you if it's finished. I just wanted to start the pull request, so you can see "live" each commit and be able to review it immediately. I thought, that it might suit, if I ask some question here, instead of creating a new issue everytime. So "all" questions about the code will be here. Is that okay for you?

2021-02-16 09:47 UTC, TornaxO7 commented
So here comes the first question: In your `vimtex#options#init()` you're calling a lot of init-script-functions. Did you wrote them all at a specifique file or do I have to find them on my own? Because otherwise I'm gonna use `grep` to find each implementation of the function xD

2021-02-16 10:06 UTC, TornaxO7 commented
Hmm.... I'm not sure, but if I continue like that, the documentation might be too detailed (I think). What do you think @lervag ? Because I think that it's easy to understand, what the `vimtex#options#init()` function does. So one to 3 sentences should be fine.

2021-02-18 22:05 UTC, lervag commented
> I thought, that it might suit, if I ask some question here, instead of creating a new issue everytime. So "all" questions about the code will be here. Is that okay for you?

Yes, that's sensible, thanks!

> Hmm.... I'm not sure, but if I continue like that, the documentation might be too detailed (I think). What do you think @lervag?

Yes, I think so too. I think one should aim for more or less self-documented code (although that is of course very hard). Avoid too many side effects, use good variable and function names, consistent styles, and so on. And if needed, one should comment things within the code of course.

I think the extra documentation we are discussing now should focus more on the structure and "architecture" than on the detailed level of the code. But still, I do see clear value in making the code more available through some high-level documentation, so thanks for starting this work!

2021-02-18 22:13 UTC, lervag commented on CONTRIBUTING.md
> +## Documentation
Could it make sense to have this as a top-level section with sub sections?

2021-02-18 22:13 UTC, lervag commented on CONTRIBUTING.md
> +bit too long the most should be probably self explained.
I think this is quite good as an introduction.

2021-02-18 22:13 UTC, lervag commented on CONTRIBUTING.md
> +```
The problem with adding a listing like this is that it quickly becomes out-of-date because I (and other contributors) will forget to update it. Do we really need to list all of this?

What's the main intent? Perhaps the structure? How about taking it one step back and instead explain the intent of the directories themselves, and not the individual files? We can point the user to the relevant sections in the vim help docs (e.g. `:help autoload`, `:help ftdetect`, etc).

2021-02-18 22:13 UTC, lervag commented on CONTRIBUTING.md
> +take a look, how vimtex initialises:
I propose to make initialization into a sub section.

2021-02-18 22:13 UTC, lervag commented on CONTRIBUTING.md
> +       default values (like `g:vimtex_compiler_enabled`)
I think this is going in the right direction. The `vimtex#options#init()` is made available like this because I realized I sometimes needed it even when not really loading the full plugin (e.g. if you only want the syntax highlighting part).

I think I would say that setting the options are the main part and should be number 1 here, while defining highlight groups is "less important". Also, it is important to use correct names here: there is no such thing as `vim-error-msg`. There is a group called `VimtexError`, though.

2021-02-18 22:13 UTC, lervag commented on CONTRIBUTING.md
> +So how does vimtex start? Well, it calls the `vimtex#init()` function at the
Please note that the plugin should be referred to as VimTeX (see latest release notes). :)

2021-02-18 23:02 UTC, TornaxO7 commented on CONTRIBUTING.md
> +## Documentation
I agree or should we create an extra-file like `DOCUMENTATION.md`?

2021-02-18 23:06 UTC, TornaxO7 commented on CONTRIBUTING.md
> +```
> The problem with adding a listing like this is that it quickly becomes out-of-date because I (and other contributors) will forget to update it. Do we really need to list all of this?

You're right. I've got another idea: Let's create a table of contents, which should represent the *directory*-structure of VimTex. So if someone `VimTex/autoload/vimtex/compiler`, than he/she just needs to click on this path in the TOC and gets a short description about the directory.

> How about taking it one step back and instead explain the intent of the directories themselves, and not the individual files?

Aye!

> We can point the user to the relevant sections in the vim help docs (e.g. :help autoload, :help ftdetect, etc).

Yes, I'd also like to add a link to [this](https://learnvimscriptthehardway.stevelosh.com/) awesome book which taught me vimscript ;)

2021-02-22 19:36 UTC, lervag commented on CONTRIBUTING.md
> +## Documentation
Good question. I think both alternatives work. But perhaps adding a new file is better? Then we can link to both `CONTRIBUTING.md` and `DOCUMENTATION.md` from "everywhere". :)

2021-02-22 19:38 UTC, lervag commented on CONTRIBUTING.md
> +```
> You're right. I've got another idea: Let's create a table of contents, which should represent the _directory_-structure of VimTex. So if someone `VimTex/autoload/vimtex/compiler`, than he/she just needs to click on this path in the TOC and gets a short description about the directory.

I'm not sure I fully understand... "So if someone `VimTex/autoload/vimtex/compiler`" - I think you forgot a verb in the sentence...?

> Yes, I'd also like to add a link to [this](https://learnvimscriptthehardway.stevelosh.com/) awesome book which taught me vimscript ;)

Yes, feel free to add a link in the code documentation resource. I agree it is a good resource!

2021-02-23 08:05 UTC, TornaxO7 commented
Ok, I added the `DOCUMENTATION.md`. 
> I'm not sure I fully understand... "So if someone VimTex/autoload/vimtex/compiler" - I think you forgot a verb in the sentence...?

The table of contents represents what I meant and you're right, I meant `So if someone wants to know something about vimtex/autoad/vimtex/compiler`, but I forgot the other half of my sentence xD.

2021-02-23 08:09 UTC, TornaxO7 commented
Oh no, I did `git fetch` before to be up to date (I thought that it wouldn't be bad, if I would do that ._.). Should I create a new pull request/branch or it fine for you (or do you have an idea, how I can fix that?)?.

2021-02-24 07:31 UTC, lervag commented
> Oh no, I did `git fetch` before to be up to date (I thought that it wouldn't be bad, if I would do that ._.). Should I create a new pull request/branch or it fine for you (or do you have an idea, how I can fix that?)?.

I don't think it matters too much while developing. We can fix the Git tree
after.

If you want to stay on top of master, then you should probably use `git fetch`, then `git rebase master`. Try to keep your commits in a single "thread". This often means you need to do a force push if you want to move your work on top of master - I'm perfectly fine with that.

The main drawback of "messy" commits is that I won't merge that "as is" - I might squash it or clean it up myself before merge. This might change the commit author metadata as a consequence. :\

Soo, to conclude: feel free to do as you want. As long as the suggested changes between the PR and the master branch reflect what you want, I'm happy.

----

In your last version, there seems to be a lot of new html files. Was that on purpose?

2021-02-24 08:31 UTC, TornaxO7 commented
> In your last version, there seems to be a lot of new html files. Was that on purpose?

No it wasn't. I thought that this directory came up, when I executed `git fetch` but after taking a look into this directory I think that I paste it from somewhere. I removed it now.

2021-02-25 09:06 UTC, TornaxO7 commented
Ok, I've got a question about the `vimtex/autoload/unite/sources`: I saw that it's doing something with the table of contents. So if I've understood it right, `vimtex/autoload/unite/sources/vimtex.vim` has some functions, which are used to generate the TOC (if we use the `:VimtexTocOpen` command)?

2021-02-25 09:38 UTC, lervag commented
> Ok, I've got a question about the `vimtex/autoload/unite/sources`: I saw that it's doing something with the table of contents. So if I've understood it right, `vimtex/autoload/unite/sources/vimtex.vim` has some functions, which are used to generate the TOC (if we use the `:VimtexTocOpen` command)?

This file is there to add the ToC unite source, see `:help vimtex-unite` (which is part of the `vimtex-toc` section). I don't think it needs much more explanation, except perhaps a like to the `unite` repo?

2021-02-25 13:44 UTC, TornaxO7 commented
# Question
What's the usage of `autoad/vimtex/cache.vim`?

2021-02-25 13:49 UTC, lervag commented
> What's the usage of `autoad/vimtex/cache.vim`?

Well, caching..?

It defines a set of functions that make it quite easy to create and uses caches, both persistent and non-persistent caches. This is very useful to speed some types of things up, e.g. calls to `kpsewhich`.

2021-02-25 14:40 UTC, TornaxO7 commented
> to create and uses caches, both persistent and non-persistent caches.
This information is what I needed! Thank you :)

# Question
What is the main usage for `autoload/vimtex/delim.vim`?

2021-02-28 22:40 UTC, lervag commented
> This information is what I needed! Thank you :)

My pleasure :)

> What is the main usage for `autoload/vimtex/delim.vim`?

A couple of things:

1. It specifies an API for parsing various types of delimiters, as well as some "actions" on delimiters.

2. The `...#init_buffer()` function is called when a VimTeX buffer is loaded and defines e.g. the `<plug>(vimtex-delim...)` mappings that are mapped to functions. E.g. `<plug>(vimtex-delim-toggle-modifier)` which does `...#toggle_modifier`. The `<plug>` mappings are given default "targets" in the function `s:init_default_mappings` in `autoload/vimtex.vim`, see e.g. here:

    https://github.com/lervag/vimtex/blob/d99f8ff57a13323d5d2fe7f3163679848bca334e/autoload/vimtex.vim#L141-L147

Note that `#init_buffer()` is found in several files. See the function `s:init_buffer` in `autoload/vimtex.vim`: it loads the `init_buffer()` function in every file where it exists. This gives an interface to easily add new "modules" with new features to VimTeX.

2021-03-07 11:46 UTC, lervag commented
I realize this recent answer can be useful to you here as well:

https://github.com/lervag/vimtex/issues/1981#issuecomment-792263781

2021-03-07 14:48 UTC, TornaxO7 commented
I don't really know where the `latex` directory came from. So I just removed it since it looks like that it was from me (sorry).

2021-03-07 14:50 UTC, TornaxO7 commented
# Question
I went through the `debug.vim` file. As far as I understood, it should create the stacktrace for the quickfix window. Now I'm unsure what kind of errors it uses. Does it fill the quickfix entries with the errors which come up from a LaTeX-Compiler or does it create the entries from vim itself? For example if you called an unknown function?

2021-03-07 20:00 UTC, lervag commented
> I went through the `debug.vim` file. As far as I understood, it should create the stacktrace for the quickfix window.

Yes and no. It creates a stacktrace and allows to pass it to the quickfix window if there is an argument. That is, if you call it with any argument (regardless of how many and what they are), the stacktrace is inserted into the quickfix window. If not, then it only returns the stacktrace as a list.

> Now I'm unsure what kind of errors it uses. Does it fill the quickfix entries with the errors which come up from a LaTeX-Compiler or does it create the entries from vim itself? For example if you called an unknown function?

This is internal debugging and is not related to LaTeX at all. What it does it that it parses the stacktrace from the `v:throwpoint` variable (see `:h ...`). If this does not exist, then we forcibly create it and remove the top element. It uses a couple of internal mechanisms to attempt to decipher the script local names (i.e. the `s:` in `function! s:myfunc` is appointed an internal number).

It should be quite easy to test it: just add `call vimtex#debug#stacktrace(1)` in some part of VimTeX that is loaded and see how it loads the trace into the quickfix list when you open a tex file.

2021-03-10 13:29 UTC, TornaxO7 commented
# Question
What is the purpose of `vimtex/autoload/vimtex/context/cite.vim`? `vim-language-server` can't find any references to the autoload-function `vimtex#context#cite#new`.

2021-03-10 13:31 UTC, lervag commented
Try this:

```vim
function! Test() abort
  try
    throw "oops"
  catch
    call vimtex#debug#stacktrace(1)
  endtry
endfunction
```

2021-03-10 13:47 UTC, TornaxO7 commented
# Question
What's the purpose of `vimtex/autoload/vimtex/parser/vimcomplete.bst`? It looks like a snippet file for me.

2021-03-10 14:20 UTC, lervag commented
> What is the purpose of `vimtex/autoload/vimtex/context/cite.vim`? `vim-language-server` can't find any references to the autoload-function `vimtex#context#cite#new`.

It provides the citation context for the context menu, see `vimtex/autoload/vimtex/context.vim`. The latter automatically finds all context entries (currently, only `cite.vim` exists) and loads them.

See `vimtex#contex#init_state`. The `s:handlers` variable is defined at the script level and is a list of all files under `context/*.vim`, so you see the `vimtex#context#{l:handler}#new()` will be called with `l:hander = 'cite'`.

The same or a similar mechanism is used other places as well, e.g.

* for the state initialization in `vimtex#state#init() -> s:vimtex.new(...)` with calls to `vimtex#{l:mod}#init_state`.
* in `vimtex#init() -> s:init_buffer()` with the `s:modules` variable.

> What's the purpose of `vimtex/autoload/vimtex/parser/vimcomplete.bst`? It looks like a snippet file for me.

It is used by `parser/bib.vim` in the `s:parse_with_bibtex()` function, which will actually run the `bibtex` problem with the supplied `.bst` file in order to convert a `.bib` file to a `.bbl` file that is much easier to parse.

2021-03-10 14:59 UTC, TornaxO7 commented
Ok so the `DOCUMENTATION.md` should be finished now. It should provide a rough overview of the plugin. You can start to review it now!

2021-03-11 21:40 UTC, lervag requested changes
Thank you, I much appreciate this effort, and I agree this venture will become valuable. I have some comments, I hope you don't mind.

I also propose that I make a revision on top after we settle my comments. I want to clean up the language a little bit and perhaps add some more content/context where needed.

2021-03-11 21:40 UTC, lervag commented on CONTRIBUTING.md
> +<!-- DON'T EDIT THIS SECTION, INSTEAD RE-RUN doctoc TO UPDATE -->
I can see the value of doctoc, but I don't expect this file to change that much, so I would propose to remove the auto update tags.

2021-03-11 21:40 UTC, lervag commented on CONTRIBUTING.md
> +new issue!
I propose to simplify this. Instead of a section, just add a short remark in the "Documentation style" section with a reference. Don't comment on the state of `DOCUMENTATION.md`, because it will change and we might forget to update this file.

2021-03-11 21:40 UTC, lervag commented on DOCUMENTATION.md
> +Welcome to the high-level documentation of **VimTex**.
I'm not sure if it is a good idea to highlight VimTeX (note capital X as in TeX). I don't do that in the README file either.

2021-03-11 21:40 UTC, lervag commented on DOCUMENTATION.md
> +# autoload
I would add a simple introduction here with a reference to Vims help files (`:help autoload`).

2021-03-11 21:40 UTC, lervag commented on DOCUMENTATION.md
> +This directory has the following health-checks functions:
Also refer to neovim docs: `:help health.nvim`  (point out this is neovim only).

2021-03-11 21:40 UTC, lervag commented on DOCUMENTATION.md
> +## vimtex
I would consider to also comment `vimtex.vim`, which is the main "entry point" in the sense of `vimtex#init()` - this functions loads most of the functionality from all the other files/modules.

2021-03-11 21:40 UTC, lervag commented on DOCUMENTATION.md
> +```tex
I prefer to keep an empty line between text paragraphs and code listings.

2021-03-11 21:40 UTC, lervag commented on DOCUMENTATION.md
> +    " create a new cache (if the name doesn't exist yet)
I use two spaces for indentation throughout, so I suggest we use that here as well.

2021-03-11 21:40 UTC, lervag commented on DOCUMENTATION.md
> +### compiler
I would refer to `compiler.vim`, not the directory - the module is the main thing of interest, the directory only contains submodules.

2021-03-11 21:40 UTC, lervag commented on DOCUMENTATION.md
> +        for more information). If this does not exist, then we forcibly create
why indent here?

2021-03-11 21:40 UTC, lervag commented on DOCUMENTATION.md
> +### complete (dir)
Again, focus on `complete.vim` - the directory should be mentioned afterwords or as part of that section.

2021-03-11 21:40 UTC, lervag commented on DOCUMENTATION.md
> +The single file (`cite.vim`) is used for the `vimtex-context-citation` part.
As before: `context.vim` is more important than the subdir. The subdir only holds the sub modules.

2021-03-11 21:40 UTC, lervag commented on DOCUMENTATION.md
> +### parser
`parser.vim`

2021-03-11 21:40 UTC, lervag commented on DOCUMENTATION.md
> +### qf
`qf.vim`

2021-03-11 21:40 UTC, lervag commented on DOCUMENTATION.md
> +### syntax
Here you should first mention `syntax.vim` - but in this case there is actually a slight deviation from the earlier schemes in that `syntax/core.vim` is the _main_ syntax functionalities. `syntax.vim` is more of a utility module - it does not really provide the real synax specific features. In hindsight, I think this was a slight mistake on my part, but I don't think it is a big problem as long as we are documenting it properly.

2021-03-11 21:40 UTC, lervag commented on DOCUMENTATION.md
> +### text_obj
I would use `text_obj.vim` as the title (and similar throughout) to make it clear that it is not a directory, but a file.

2021-03-11 21:40 UTC, lervag commented on DOCUMENTATION.md
> +### view
`view.vim` vs the sub modules.

2021-03-11 21:40 UTC, lervag commented on DOCUMENTATION.md
> +
I propose to rearrange the order:

- [ftplugin](#ftplugin)
- [syntax](#syntax-1)
- [indent](#indent)
- [after/ftplugin](#afterftplugin)
- [autoload](#autoload)
- [rplugin/python3/denite/source/vimtex.py](#rpluginpython3denitesourcevimtexpy)
- [test](#test)

The reason is twofold: First, the first sections will be short, because the bulk code is in autoload. My suggested ordering also indicates some sort of "importance", in that VimTeX is a filetype plugin, and the main entry point of the plugin is the `ftplugin` directory. It is also a syntax plugin and an indent plugin.

2021-03-11 21:40 UTC, lervag commented on DOCUMENTATION.md
> +### fold
As before: `fold.vim` > `fold/*.vim`

2021-03-11 21:40 UTC, lervag commented on DOCUMENTATION.md
> +stable and functional awesome VimTex plugin :) Each directory and filename
Hehe, thanks :)

But let's keep it simple and remove "awesome" and the similey. ;)

2021-03-11 23:29 UTC, TornaxO7 reviewed
Oh damn. I didn't wanted to create a "review". I thought that I could response to you messages by clicking on this `review` button... sorry for doing this mess! ._.

2021-03-15 10:44 UTC, lervag commented
> Oh damn. I didn't wanted to create a "review". I thought that I could response to you messages by clicking on this review button... sorry for doing this mess! ._. You can delete these comments starting from this one if you want (I can't delete them somehow).

No worries. I'll just respond inline here and look over the updates afterwards.

> (Neo)Vim did that automatically for me. I fixed that now.

The context here is, I think, the indendation: I guess you have `autoindent` and smilar options enabled, perhaps even `cindent`.

> I'm unsure what to write there instead. Could you do this for me or can you provide me some tipps?

Yes, no problem.

2021-03-15 10:58 UTC, lervag commented
Thank you for this, I think it can bring a lot of value! I'll add some commits on top with some updates, and feel free to continue contributing if you have more ideas (either docs or other things)! :)

2021-03-15 10:58 UTC, closed without merging

2021-03-15 14:03 UTC, lervag commented
I've pushed a couple of additional commits on top of this now, and I think it has become quite good. Feel free to suggest more improvements.