Fix(syntax): \lstset syntax highlighting
lervag/vimtex pull request #2001
Opened 2021-03-22 18:16 UTC by 144026

## Fixes #2000 

### Before fix
![image](https://user-images.githubusercontent.com/44112701/112018868-e6816a00-8b69-11eb-8131-3e027cf72eb0.png)

**Note** that the red `}` is somehow classified into a `texGroupError`:
![image](https://user-images.githubusercontent.com/44112701/112019720-ab336b00-8b6a-11eb-9b40-f8ba4056b35b.png)

### After fix
![20210322235220](https://raw.githubusercontent.com/144026/rsrc/master/img/20210322235220.png)

2021-03-22 19:30 UTC, lervag commented
Thanks! I assume #1999 was a duplicate as well? I'll look into this asap. I'll close #2000 and, if necessary, we'll discuss the related issue here. I hope that's OK by you.

2021-03-22 20:21 UTC, 144026 commented
Thanks! I got something wrong in #1999 so I closed it, and opened this PR after I got things work.

2021-03-22 20:36 UTC, lervag requested changes
Nice work, thanks! I had a very minor comment - I could probably just do that myself, but I also think it was worth suggesting it to allow a reply/additional comment.

2021-03-22 20:36 UTC, lervag commented on autoload/vimtex/syntax/p/listings.vim
> +  highlight def link texLstsetGroup   texGroup
Actually, I think this should simply be deleted. The group itself should have no highlighting. Only the content and delimiters should be highlighted.

2021-03-23 04:36 UTC, 144026 commented on autoload/vimtex/syntax/p/listings.vim
> +  highlight def link texLstsetGroup   texGroup
OK! I did that because the general `texGroup`(usually appear as `\texCmd{texGroup}`) isn't highlighted as well. And if someone would like to change `texGoup`'s highlight, `texLstsetGroup` would always stay consistent.

Simply delete this line is aslo reasonable, I will do this later today.

2021-03-23 08:56 UTC, lervag commented
Again, thanks! When I looked at it now, I realized: the reason I had the `texLstsetGroup` linked to `texOpt` was to make it look similar to the other option groups. I.e., to make the `\lstset{...}` argument look similar to the option group for `\begin{lstlisting}[...]`. I agree that it _looks_ inconsistent. Perhaps a better idea is to rename that group, e.g. `texLstsetOptarg` or similar. I have to admit, naming things is difficult! A pragmatic choice is to leave this as it was (linked to `texOpt`), but renaming it (and keeping the link) may be better.

2021-03-23 12:59 UTC, lervag commented on autoload/vimtex/syntax/p/listings.vim
> +        \ nextgroup=texLstsetArg,texLstsetArg skipwhite skipnl
No need for duplicate `texLstsetArg`. :)

2021-03-23 13:01 UTC, lervag commented
Yes, `texLstsetArg` might actually work very well. The reason I did not suggest it was because there is already a more specific `texLstsetArg` group; however, I don't think it is a problem. If the tests pass and things look good on your end, then I think we'll settle for this solution. If there should be any issues with it, we can solve them as they come.

2021-03-23 13:06 UTC, 144026 commented
OK! I renamed it to `texLstsetArg` (similar to `texTikzsetArg` for `\tikzset`), and linked it to `texOpt` again.

2021-03-23 15:01 UTC, lervag commented
> **OK! Both github-ci and my local tests seem ok for now.** I think the `\lstset` problem is almost settled.

Great!

> But I would like point out why I did once choose to link to `texGroup`: (although it's out of the `\lstset` problem`)
> 
> The highlight for `texCmd` and `texOpt` are the same (under my base16 colorscheme), and it looks quite odd when I write multiple lines of `texOpt` & `texCmd` together:

Ah, I see. They are not really the same, actually. See here:

https://github.com/lervag/vimtex/blob/1ef97f079133d35f754d79641cc73764adfe2a76/autoload/vimtex/syntax/core.vim#L480-L494

`texCmd` is by default linked to `Statement`, while `texOpt` is linked to `Identifier`. These groups should have different highlighting according to `group-name`. Thus, I would propose that this problem is really a problem with your colorscheme. You could either fix that "upstream", or you could apply some changes to your tex highlighting by customising the colors manually.

2021-03-23 15:01 UTC, closed without merging

2021-03-23 15:02 UTC, lervag commented
I think this was already good now, so I merged. Feel free to suggest further improvements/adjustments (either PR or issues).