Allow optional group and more than one mandatory argument in nospell commands
lervag/vimtex pull request #2118
Opened 2021-07-27 01:11 UTC by tornaria

When a command is in `g:vimtex_syntax_nospell_commands`, its argument is excluded from spell checking; after the first patch this also works for commands with an optional argument.

After the second patch, a command in `g:vimtex_syntax_nospell_commands` can have more than one mandatory argument; spell check is disabled for all of them.

I use this for custom commands with optional arguments; also for some standard commands like `\numberwithin` (2 mandatory arguments).

2021-07-27 10:15 UTC, lervag requested changes
Great, thanks. I don't see any reason not to accept this, except my minor comment.

2021-07-27 10:15 UTC, lervag commented on autoload/vimtex/syntax/core.vim
> +  highlight def link texNoSpellArg         texArg
I'm not sure if we really want to add the default highlight for `texNoSpellArg` here. Users can add that if they want, but I thought it OK to just keep it transparent.

2021-07-27 16:09 UTC, tornaria commented on autoload/vimtex/syntax/core.vim
> +  highlight def link texNoSpellArg         texArg
You are right, done.

2021-07-28 09:09 UTC, lervag commented
Thanks!

2021-07-28 09:09 UTC, closed without merging