Fix zathura inverse search on NixOS
lervag/vimtex pull request #2262
Opened 2021-11-30 01:49 UTC by poscat0x04

closes #2261

2021-11-30 20:24 UTC, lervag commented
Thanks for raising an issue and also proposing a resolution!

2021-11-30 20:25 UTC, lervag commented on autoload/vimtex/view/zathura.vim
> +let s:inverse_search_cmd = get(g:, 'vimtex_view_zathura_vim_path', get(v:, 'progpath', get(v:, 'progname', '')))
Although this is currently used only for Zathura, I think it could be wise to use a more general name. How about `g:vimtex_callback_progpath` or simply `g:vimtex_progpath`?

2021-11-30 20:27 UTC, lervag requested changes
I only have minor comments. Let me know what you think.

2021-11-30 20:27 UTC, lervag commented on autoload/vimtex/view/zathura.vim
> +let s:inverse_search_cmd = get(g:, 'vimtex_view_zathura_vim_path', get(v:, 'progpath', get(v:, 'progname', '')))
Also, I prefer to keep lines below 80 columns unless there's a good reason not to.

2021-11-30 20:27 UTC, lervag commented on doc/vimtex.txt
> +  The path to the vim binary that will be passed to Zathura. If unset, vimtex
I would generalize this text somewhat and raise Zathura as an example.

2021-12-01 01:16 UTC, poscat0x04 commented on autoload/vimtex/view/zathura.vim
> +let s:inverse_search_cmd = get(g:, 'vimtex_view_zathura_vim_path', get(v:, 'progpath', get(v:, 'progname', '')))
fixed

2021-12-01 01:16 UTC, poscat0x04 commented on doc/vimtex.txt
> +  The path to the vim binary that will be passed to Zathura. If unset, vimtex
done.

2021-12-01 01:41 UTC, poscat0x04 commented
I've tested this PR on my machine and it works.

2021-12-01 21:56 UTC, lervag commented
Thanks!

2021-12-01 21:56 UTC, closed without merging