refactor skim viewer
lervag/vimtex pull request #2289
Opened 2021-12-29 16:31 UTC by clason

Refactor the Skim viewer backend to
* use JavaScript instead of AppleScript (nicer, and should fix #2279)
* make the initial start respect `g:vimtex_view_skim_activate`
  (alternative to #2286, @yongrenjie )
* factor out common script parts into `self` variables
* correct off-by-one line number for forward search
* introduce new option `g:vimtex_view_skim_sync` to perform forward
  search after compilation (syncing viewer and editor), default true
* change default for `g:vimtex_view_skim_reading_bar` to false (location
  is highlighted anyway on sync)

2021-12-30 11:58 UTC, lervag commented
> * use JavaScript instead of AppleScript (nicer, and should fix [Skim forward search not working on macOS 12.1 #2279](https://github.com/lervag/vimtex/issues/2279))

Great!

> * make the initial start respect `g:vimtex_view_skim_activate`  (alternative to [add option to control whether Skim gets focus upon first open #2286](https://github.com/lervag/vimtex/pull/2286), @yongrenjie )

Great!

> * factor out common script parts into `self` variables

Not quite sure if this has any specific merits..?

> * correct off-by-one line number for forward search

Great!

> * introduce new option `g:vimtex_view_skim_sync` to perform forward  search after compilation (syncing viewer and editor), default true

Does this sync on _every_ callback, or just the initial one? I believe there may be three main categories here:

* The user does not want any forward search when the viewer starts or on callbacks.

* The user wants a forward search just when the viewer starts (either manually or through callback).

* The user wants forward search on every callback.

> * change default for `g:vimtex_view_skim_reading_bar` to false (location is highlighted anyway on sync)

I don't have any opinions on this.

2021-12-30 12:19 UTC, lervag requested changes

2021-12-30 12:19 UTC, lervag commented on autoload/vimtex/view/skim.vim
> +        \ g:vimtex_view_skim_sync ? self.sync : '',
Do I remember correctly that this stuff is required to force Skim to update after successful compilation? I.e., without this, Skim would still show the old version of the PDF?

If possibly, I think it would be good to add support for `g:vimtex_view_automatic` here similar to how it's done for Zathura and MuPDF, see here:

https://github.com/lervag/vimtex/blob/f31b723d16fa00137ccbe51fa771a90dc642b05d/autoload/vimtex/view/_template.vim#L236-L253

2021-12-30 12:19 UTC, lervag commented on autoload/vimtex/view/skim.vim
> +      \]),
I think the main purpose for adding these variables as dictionary keys is to prevent duplicate code. As far as I can see, the `start` key is only used once. `show` and `sync` are used twice. I therefore believe it would be better to remove the `start` key and instead type it out verbosely (unless we end up removing the `_latexmk_append_argument` stuff altogether). I'm also wondering if the code could be slightly cleaner if the `show` and `sync` keys are instead changed to script variables; it would never make sense for a user outside of this scripts scope to inspect these variables, right?

2021-12-30 12:19 UTC, lervag commented on autoload/vimtex/view/skim.vim
> +        \ g:vimtex_view_skim_sync ? self.sync : '',
Is it possible to implement an `_exists` method that would be reliable for Skim?

2021-12-30 12:23 UTC, clason commented
> Not quite sure if this has any specific merits..?

Makes it a bit easier to maintain (it's hard enough not to lose track of all the quotes for the embedded scripting...). An alternative would be to move the complete thing out into a (private) `view` function that takes options to control the behavior, depending on whether it's run from a callback or a forward search.

> Does this sync on every callback, or just the initial one? I think there are two different scenarios here:

It syncs on every callback. I agree that this may not be desirable (in fact, my motivation for the original refactor to get rid of `displayline` was exactly _not_ to do that ;)), but there's a tradeoff here between features and complexity; this strikes me as a reasonable one, at least as long as VimTeX doesn't easily provide the information whether it's the first callback or subsequent ones?

2021-12-30 12:25 UTC, clason commented on autoload/vimtex/view/skim.vim
> +        \ g:vimtex_view_skim_sync ? self.sync : '',
No, that is for doing a forward search (syncing editor and viewer, which I know some people like). The update happens in every case (via the `app.revert(theDocs)` line) as I don't see any reason _not_ to have this.

2021-12-30 12:26 UTC, clason commented on autoload/vimtex/view/skim.vim
> +        \ g:vimtex_view_skim_sync ? self.sync : '',
I can, however, put this behind a `g:vimtex_view_automatic` guard -- if there is a good reason for it?

2021-12-30 12:28 UTC, clason commented on autoload/vimtex/view/skim.vim
> +      \]),
I think the main question is when the config variables are evaluated. I believe the reason to have them in the template is to allow updating it via `:VimtexReload`?

But this relates to the comment below: I'm happy to do the refactoring in another way; I just wanted to stay as close to the current setup as I don't fully understand the control flow here.

2021-12-30 12:38 UTC, clason commented
I think there are three scenarios:
1. a forward search, which I believe should sync unconditionally (after all, that's the meaning of "forward search");
2. a compiler callback, which some people would like to keep synced while others would hate that, hence should be an option;
3. a compiler callback that also starts the viewer -- optionally followed by a forward search, which I believe most people would want.

As far as I can tell, the current architecture doesn't allow me to easily handle 3., since VimTeX itself doesn't know about this, and the `latexmk` option can't run vimscript functions?

2021-12-30 13:21 UTC, clason commented
@lervag I've refactored again to extract all the common JavaScript lines into a single `make_cmd_view` script-level _function_; that indeed looks cleaner (although the nested ternary is rather ugly).

The `sync` now defaults to `false` to preserve old behavior; I think this is now a strict improvements. Further improvements are possible but would need some architecture changes, I believe.

2021-12-31 13:14 UTC, lervag commented
Thanks @clason! I've merged now. But please note: I've made some important general changes based on the discussion we've had. I've now forced `-view=none` with the latexmk backend so as to have full control of the viewer from vimtex. I expect this to fail somewhat, actually, but I believe it is better to address those issues and find a more robust solution than to stay intertwined with latexmk.

So: Please test the latest version and let me know how it works. Especially: with the default settings with Skim, do things still work as expected?

2021-12-31 13:14 UTC, closed without merging

2021-12-31 13:21 UTC, clason commented
Yes, looks fine to me! Except for the reading bar, I get the same behavior as before with the default settings (and `g:vimtex_view_skim_sync` works as expected).

2021-12-31 13:23 UTC, lervag commented
Does Skim start automatically after compilation?

Also, I think we want to support `g:vimtex_view_automatic` also for Skim.

2021-12-31 13:32 UTC, clason commented
> Does Skim start automatically after compilation?

Yes, it does.

> Also, I think we want to support `g:vimtex_view_automatic` also for Skim.

Why (honestly asking)? From what I've seen, this is optional since for many viewers, it requires workarounds using external tools and whatnot, which may have undesired side effects (such as slowdown). However, Skim supports this out of the box with the same interface, so it's a freebie. 

Can you think of any situation where you would _not_ want this?

2021-12-31 13:32 UTC, lervag commented
Ok, so, to be more clear about what I'm thinking about, please see how the general viewer now works wrt. callbacks:

https://github.com/lervag/vimtex/blob/72e6285b91a606940ec21c8cd5e587f842094ca4/autoload/vimtex/view/_template.vim#L80-L91

The callbacks are "activated" here (they are active in all cases):

https://github.com/lervag/vimtex/blob/72e6285b91a606940ec21c8cd5e587f842094ca4/autoload/vimtex/view.vim#L25-L29

And this shows how they are abstracted:

https://github.com/lervag/vimtex/blob/72e6285b91a606940ec21c8cd5e587f842094ca4/autoload/vimtex/view.vim#L50-L66

2021-12-31 13:34 UTC, lervag commented
> Why (honestly asking)? From what I've seen, this is optional since for many viewers, it requires workarounds using external tools and whatnot, which may have undesired side effects (such as slowdown). However, Skim supports this out of the box with the same interface, so it's a freebie.
> 
> Can you think of any situation where you would _not_ want this?

Yes, simple: I don't want `\ll` to open the viewer automatically. So, I add `let g:vimtex_view_automatic = 0` to prevent it. That just works. I use `\lv` to open the viewer when I want it.

Currently, this workflow is not possibly with Skim, because it does not support `g:vimtex_view_automatic`.

2021-12-31 13:37 UTC, clason commented
Interesting. But I don't see the issue then: Isn't it trivial to add that approach to the current callback, as in
```vim
function! s:viewer.compiler_callback(outfile) dict abort " {{{1 
   if !g:vimtex_view_automatic 
       \ || has_key(self, 'started_through_callback') | return | endif 
  
   call vimtex#jobs#run(s:make_cmd_view(a:outfile, g:vimtex_view_skim_sync))
   let self.started_through_callback = 1 
 endfunction 
```

2021-12-31 14:22 UTC, lervag commented
For other people reading here - me and @clason discussed things on Gitter and I've pushed a few more updates that we believe resolve these things for now. Feel free to open new issues if something broke!