Adjust path parsed result for pplatex
lervag/vimtex pull request #2369
Opened 2022-04-08 14:05 UTC by JingMatrix

Latex log assumes project root to be the start directory

2022-04-09 09:35 UTC, lervag requested changes
I don't see any reason not to accept, but I'll allow you to adjust as commented.

2022-04-09 09:35 UTC, lervag commented on autoload/vimtex/qf/pplatex.vim
> +  execute 'lcd' b:vimtex.root
It would be better to use the built-in api: `call vimtex#paths#pushd(b:vimtex.root)`.

Similar to how it's done in `jobs#run`:

https://github.com/lervag/vimtex/blob/master/autoload/vimtex/jobs.vim#L40-L42

2022-04-09 09:35 UTC, lervag commented on autoload/vimtex/qf/pplatex.vim
> +  execute 'lcd' l:pwd
`call vimtex#paths#popd()`

2022-04-09 11:20 UTC, JingMatrix commented
I force updated my commit now, the first one is a rebase for your commits, and the second one is to adopt your advices.

Thanks for your advice on `popd` and `pushd`, it is intuitive just as the shell language.

2022-04-10 20:19 UTC, lervag commented
Great, thanks! I'll merge now. :)

2022-04-10 20:20 UTC, merged