Use json to store fontawesome icons
lervag/vimtex pull request #2528
Opened 2022-10-24 08:42 UTC by Freed-Wu

Add a github workflow to check if a json is sorted

2022-10-24 08:57 UTC, lervag requested changes
Thanks! I'll have to check this before accepting. You can also check. I would actually not be surprised if this now fails at `\faFile*`.

Can you explain the github workflow for me? I'm not an expert on that, and I'm curious if we should make it more specific? I.e., now the workflow triggers on all json files, but that does not seem correct if there should be more json files added?

2022-10-24 08:57 UTC, lervag commented on autoload/vimtex/syntax/p/fontawesome5.vim
> +let s:fontawesome = json_decode(join(readfile(s:json_path), ''))
I prefer to have the script local stuff at the bottom and the main "public" code at the top.

2022-10-24 08:57 UTC, lervag commented on autoload/vimtex/syntax/p/fontawesome5.vim
> +    if l:name ==# '500px'
Yes, ok. But this will add a conditional on every iteration. It is small, but still, there are O(1000) symbols, so it may still be significant. Should at least check if it is relevant.

2022-10-24 10:51 UTC, Freed-Wu commented
> Can you explain the github workflow for me

```sh
          for json in assets/json/*.json ; do
            diff <(jq -S . $json) $json || exit 1
          done
```

if a json is not sorted, jq -S . will sort it and print the sorted json to 
stdout, so diff the stdout and original json will return 1, `|| exit 1` will 
quit the for-loop, Like this:

[screenshot](https://user-images.githubusercontent.com/32936898/197423696-c44a5f2b-45d5-4c40-9d85-1191f7e786c5.png)

2022-10-24 10:51 UTC, Freed-Wu commented on autoload/vimtex/syntax/p/fontawesome5.vim
> +let s:fontawesome = json_decode(join(readfile(s:json_path), ''))
OK, I'll fix.

2022-10-24 11:00 UTC, Freed-Wu commented on autoload/vimtex/syntax/p/fontawesome5.vim
> +    if l:name ==# '500px'
OK, I'll fix it.

2022-10-24 13:01 UTC, lervag commented
Thanks. As I wrote above:

> I'll have to check this before accepting. You can also check. I would actually not be surprised if this now fails at `\faFile*`.

I've checked, and as you see, it now fails:

![image](https://user-images.githubusercontent.com/998898/197531037-b92a3001-f342-4139-96a1-aad92a61807b.png)

The reason is that the Vim dictionary does not preserve a sorted order, necessarily. So, this means we must either sort the `item(DICTIONARY)` or store the data as a sorted list in the json file.

Regarding the workflow: I'm still wondering if it is a good idea to trigger this workflow on _any_ json file and to specify that all json files must be sorted? Would it not be more appropriate to restrict it to this specific file?

2022-10-24 13:33 UTC, Freed-Wu commented
> Would it not be more appropriate to restrict it to this specific file?

Fixed.

> store the data as a sorted list in the json file.

Fixed.

2022-10-26 22:00 UTC, lervag commented
I did some minor profiling, and fascinatingly, doing the `json_decode(fileread())` is faster than inlining in vimscript.

I'm merging this now. Thanks for contributing!

2022-10-26 22:09 UTC, merged

2022-10-26 22:11 UTC, lervag commented
I made a few minor changes to the workflow (https://github.com/lervag/vimtex/blob/master/.github/workflows/assets.yml), mostly that I fixed the path to the fontawesome file. That will avoid any surprises if I were to add more json files to the assets directory. I believe I should probably collect all assets within that subdirectory, so I might look into that in the not so far away future.

2022-10-26 22:24 UTC, lervag commented
Hmm. For some reason, the updated workflow does not run properly now:

https://github.com/lervag/vimtex/actions/runs/3332974138

Perhaps you could assist me here? Here's the diff of the workflow file from your version to the current:

![image](https://user-images.githubusercontent.com/998898/198149976-03e5507d-88a3-4ef6-b4e3-0f28ff13b60c.png)

2022-10-27 02:33 UTC, Freed-Wu commented
Fixed :+1:

2022-10-27 06:56 UTC, lervag commented
Thanks! I'll look into the new PRs later today!