doc: rename "recursive search" to "directory scan"
lervag/vimtex pull request #2559
Opened 2022-11-04 21:12 UTC by shuber2

The method 6 of finding the main file is based on a directory scan which is described as "recursive" scan. However, while a recursive scan suggests a (recursive) directory descent, the opposite is true: the unique ascending path of parent directories is scanned.

This is fixed in the following steps:

  1. The method is renamed to "directory scan method"
  2. The method description is adapted to reflect this behavior more clearly. In particular, it is explicitly mentioned that no recursive directory descent is performed.
  3. The option to disable this method is renamed to g:vimtex_disable_directory_scan_main_file_detection

As a side effect, the overall description of the directory scan method is reworked.

As a further side effect, the name of this method is more independent of the algorithmic mechanism, but rather reflects the policy, cf. "policy versus mechanism" paradigm.

2022-11-04 21:26 UTC, shuber2 commented
@lervag Sorry, I was not thinking you would be that quick with the work on the other issue. So this pull request will have merge conflict with #2557.

2022-11-05 15:07 UTC, lervag commented
> The method 6 of finding the main file is based on a directory scan which is described as "recursive" scan. However, while a recursive scan suggests a (recursive) directory descent, the opposite is true: the unique ascending path of parent directories is scanned.

Interesting point. The reason I use "recursive" here is because it is functionally recursive in the sense that same algorithm is used recursively for complex documents, e.g. `main.tex ← chapter.tex ← section.tex`. If you open `section.tex`, it will being the search from itself, then find that `chapter.tex` contains `section.tex`. It then _recurses_ and finds `main.tex` in the next "iteration". Thus, the point of "recursive" is not about the directory descent at all, it has to do with the project graph of a multi-file LaTeX project.

I'm, curious, though, if you may still have a point with regard to user point of view. What I explained above is an implementation detail, and it is not important (in most cases) for users to care about that.

I'm curious what you think about this.

In any case, I notice that your PR also has good suggestions for how to rephrase and improve the wording, also in general. So I will want to merge it somehow, regardless of the outcome of this discussion!

> 3. The option to disable this method is renamed to g:vimtex_disable_directory_scan_main_file_detection

If we rename an option, we should put the old option in a deprecated list to guide users. That's trivial for me, so I can do it if we go this way. Or I could show you the relevant part in the code.

> As a further side effect, the name of this method is more independent of the algorithmic mechanism, but rather reflects the policy, cf. "policy versus mechanism" paradigm.

Yes, this seems to be relevant to what I wrote above.

> Sorry, I was not thinking you would be that quick with the work on the other issue. So this pull request will have merge conflict with #2558.

I have no problems with merge conflicts. It should be mostly trivial in this case, I think. I'll let you decide if you want to rebase your PR on top of the current master, or if you want me to handle the merge when we've settled the discussions.

2022-11-05 15:14 UTC, lervag commented on doc/vimtex.txt
> +that attempts to find the main LaTeX file in most cases (method 6 in the list
I'm not sure I agree with the change "should" to "attempts to". My initial point was to communicate that it will work in most cases. With your proposed change, the wording says it will try to work in most cases, which also means that it will not even try to work in some cases. But that's incorrect.

2022-11-05 15:14 UTC, lervag commented on doc/vimtex.txt
> +  3. It contains `\begin{document}` (or includes a file that does).
Thanks; your suggested changes for 453 to 457 are very good!

2022-11-05 15:14 UTC, lervag commented on doc/vimtex.txt
> +  be found as the main file.
I believe my original wording was confusing here. The use of "recursive" is not about directory decending, but about complex projects. I.e., given a project where `main.tex` includes `chapter.tex`, which again includes `section.tex`, if you open `section.tex`, then this is the recursion:

```
find_main(section.tex)
-> find_main(chapter.tex)
  -> find_main(main.tex)
```

where `find_main` will return the file argument if it is a main file, or it will recurse into any file it finds that _includes_ the given file argument.

2022-11-05 19:52 UTC, shuber2 commented on doc/vimtex.txt
> +that attempts to find the main LaTeX file in most cases (method 6 in the list
I agree, and the recent work on improving the main file detection makes your point even stronger. I have rephrased the paragraph.

2022-11-05 19:55 UTC, shuber2 commented on doc/vimtex.txt
> +  be found as the main file.
Yes, this is recursive in its nature. That is, the method to expand a tex file recursively through include (and likewise) commands is recursive. This is an implementational aspect of the "directory scan" method. I think what is relevant to the user is the following: The candidate file is expanded and the expanded file needs to meet some requirements (documentclass, begin{document}).

2022-11-05 20:03 UTC, shuber2 commented
@lervag Thank you for your feedback. I did some work on this:

- Rebase to current master
- Rephrasing to address your feedback
- Adding deprecation information in logic and doc

I also rephased the description of the directory scan method again to make the point on the recursive expansion clearer, including a reference to `g:vimtex_include_indicators`.

When it comes to the overview of methods, the essence of method 6 is that directories are scanned to find a suitable main file. In my opinion, the name of the method should therefore reflect this aspect. When we now describe details when a candidate tex file qualifies as a main file, the aspect of parsing it and recursively expanding it through included tex files becomes relevant. But this is a downstream aspect. And it is an aspect that is true for method 1-5 as well, namely checking whether a candidate tex file is a suitable main file for the current file. What distinguishes method 6 from method 1-5 is that a search for a main file is performed, i.e., directories are scanned for such a file.

2022-11-06 07:17 UTC, shuber2 commented
A minor rephrasing and a minor spelling fix added.

2022-11-06 14:42 UTC, lervag requested changes
Thanks! I think this is going in a good direction that should help make things clearer! I much appreciate your efforts, and I hope you don't find my feedback _too_ nitpicky.

2022-11-06 14:42 UTC, lervag commented on autoload/vimtex/state.vim
> +  if !get(g:, 'vimtex_disable_directory_scan_main_file_detection', 0)
I'm actually considering if we should instead just remove this option alltogether. I don't think _anyone_ uses it. If someone complained, it would be a useful feedback in itself, and I could revert that specific change and use the name you suggest here.

2022-11-06 14:42 UTC, lervag commented on autoload/vimtex/state.vim
>    for l:cand in s:findfiles_recursive('*.tex', fnamemodify(l:file, ':p:h'))
Perhaps we should rename `s:findfiles_recursive` here? And possibly the `s:get_main_recurse` as well? It seems to be in line with your suggestions here.

2022-11-06 14:42 UTC, lervag commented on autoload/vimtex/state.vim
>    for l:cand in s:findfiles_recursive('*.tex', fnamemodify(l:file, ':p:h'))
Or, perhaps the `s:get_main_recurse` is ok, since it _is_ used recursively. But `s:findfiles_recursive` could perhaps be better named as `s:findfiles_directory_scan`?

2022-11-06 14:42 UTC, lervag commented on doc/vimtex.txt
> +therefore tried prior the directory scan.
prior _to_ the?

2022-11-06 14:42 UTC, lervag commented on doc/vimtex.txt
> +  If none of the above methods gives an appropriate candidate for a main file
* gives -> give
* "for a main file _that directly or indirectly includes_ the present file"

2022-11-06 14:42 UTC, lervag commented on doc/vimtex.txt
> +  If none of the above methods gives an appropriate candidate for a main file
Or, perhaps simply: "If none of the above methods yield an appropriate main file, then a search ..."?

2022-11-06 14:42 UTC, lervag commented on doc/vimtex.txt
> +  all tex files included. Then it is checked whether all of the three
the three "following" requirements

2022-11-06 14:42 UTC, lervag commented on doc/vimtex.txt
> +  line and `\begin{docment}`; it could instead stem from included tex files.
doc**u**ment

2022-11-06 14:42 UTC, lervag commented on doc/vimtex.txt
> +  considered to include tex files by the parser for the recursive expansion.
Yes, that's good. Thanks!

2022-11-06 14:42 UTC, lervag commented on doc/vimtex.txt
> +  root directive as an alternative.
Perhaps we should just refer to _any_ of the methods 1-5, instead of only the tex root alternative?

2022-11-06 14:42 UTC, lervag commented on doc/vimtex.txt
> +        by the option |g:vimtex_disable_directory_scan_main_file_detection|.
I think we can remove this note and the option, as discussed earlier.

2022-11-06 14:42 UTC, lervag commented on doc/vimtex.txt
>    value.
See earlier comments.

2022-11-06 14:42 UTC, lervag commented on doc/vimtex.txt
> +favor of |g:vimtex_disable_directory_scan_main_file_detection|.
If we remove the option, it is still useful to give such a notice.

2022-11-06 16:20 UTC, shuber2 commented on autoload/vimtex/state.vim
>    for l:cand in s:findfiles_recursive('*.tex', fnamemodify(l:file, ':p:h'))
Had the same thoughts. But I think this should be a separate commit to make debugging with git bisect easier later. I will work on that!

2022-11-06 16:22 UTC, shuber2 commented on autoload/vimtex/state.vim
> +  if !get(g:, 'vimtex_disable_directory_scan_main_file_detection', 0)
One would like to disable it for performance reasons. The feedback on #2558 seems that suggest that this is generally not an issue, but it is hard to estimate for all actual or potential users.
I will implement the removal as a dedicated commit, so it can be cleanly reverted.

2022-11-06 16:23 UTC, shuber2 commented on doc/vimtex.txt
> +therefore tried prior the directory scan.
yes.

2022-11-06 16:25 UTC, shuber2 commented on doc/vimtex.txt
> +  If none of the above methods gives an appropriate candidate for a main file
I think "gives" is ok because the indivual, single methods are meant; it can be read as "none of the [individual] above mehtods gives". It would need to be "give" if phrased as "If the above methods give no appropriate…"

2022-11-06 16:27 UTC, shuber2 commented on doc/vimtex.txt
> +  all tex files included. Then it is checked whether all of the three
yes, makes sense.

2022-11-06 16:27 UTC, shuber2 commented on doc/vimtex.txt
> +  performed.
Yes, a ascent and descent in the directory _tree_, and (rooted) trees are typically drawn from the root downwards.

2022-11-06 16:28 UTC, shuber2 commented on doc/vimtex.txt
> +  root directive as an alternative.
That is true, well spotted.

2022-11-06 16:29 UTC, shuber2 commented on doc/vimtex.txt
> +        by the option |g:vimtex_disable_directory_scan_main_file_detection|.
See comment above. I will do that in a separate commit, so it can be atomically reverted-.

2022-11-06 16:30 UTC, shuber2 commented on doc/vimtex.txt
> +favor of |g:vimtex_disable_directory_scan_main_file_detection|.
Yes. An the removal commit would rephrase it accordingly.

2022-11-06 16:34 UTC, shuber2 commented
@lervag All good comments, thanks! And I sympathize with "nitpicking". ;)

2022-11-06 19:37 UTC, lervag commented on doc/vimtex.txt
> +  If none of the above methods gives an appropriate candidate for a main file
> I think "gives" is ok because the indivual, single methods are meant; it can be read as "none of the [individual] above mehtods gives". It would need to be "give" if phrased as "If the above methods give no appropriate…".

Ok!

> By the way, it is "If x then y", not "If x, then y". I saw the comma somewhere else arleady in the docs I think.

This is an example of a conditional subordinate conjunction, and I think you need the comma. I found a couple of semi-good references in a quick search:
* https://english.stackexchange.com/questions/373905/how-do-you-punctuate-an-if-then-when-both-the-if-and-the-then-are-implied
* https://www.ego4u.com/en/cram-up/writing/comma?10

2022-11-06 19:39 UTC, lervag commented on doc/vimtex.txt
> +  performed.
I think that's what confuses me. A tree is _naturally_ pointed upwards, but in these cases they are used _downwards_. 🤷🏻

2022-11-06 19:40 UTC, lervag commented
Thanks! I'm glad you don't mind me being pedantic. :)

Looking forward to seeing an updated PR!

2022-11-06 19:46 UTC, shuber2 commented
@lervag There we go, let's give it another try. I have split the commits up into logical, independent blocks for their own fate. In particular the commit to remove the disable-method-6 option can be easily reverted by itself.

2022-11-06 19:53 UTC, shuber2 commented on doc/vimtex.txt
> +  performed.
By "naturally" you mean biological trees? Yes. In computer science, however, trees are drawn with the root at the top, see https://en.wikipedia.org/wiki/Tree_(data_structure)

Or consider the tree shell command or file browsers.

2022-11-06 20:15 UTC, lervag commented
Thanks! I've merged this now after making a few minor changes. Please feel free to let me know if you disagree with them, specifically this commit: https://github.com/lervag/vimtex/commit/af05c7b0c7a4ae05733e1832b39cfa9e57edd694.

2022-11-06 20:15 UTC, closed without merging

2022-11-06 20:19 UTC, lervag commented
Oh, and by the way: I very much appreciate this contribution. Documentation is important and hard! And this is actually a very important part of the docs. I hope and believe your contribution here may help make this stuff clearer to both new and existing users in the future, and as such, I think it is a very valuable contribution!

2022-11-06 20:22 UTC, shuber2 commented
Thank you very much!