Update docs to explain customization of `foldtext`
lervag/vimtex pull request #3056
Opened 2024-12-13 00:26 UTC by rhelder

As promised in #3052, here is a draft explaining how to customize the text displayed when folds are closed. For readers who are less familiar with dictionary functions, I included both the more verbose and the more concise variants we discussed (with appropriate references to Vim's documentation). I expect there are changes you'll want to make, but I hope this is a good starting point!

2024-12-13 19:51 UTC, lervag requested changes
I think this is more or less perfect. Thanks! I suggested a minor update to add an example for Lua based configs.

2024-12-13 19:51 UTC, lervag commented on doc/vimtex.txt
> +<
Perhaps we should also add a Lua example? The following text would work:

```
  And for completeness, the following would work with a Lua based config: >lua

    vim.g.vimtex_fold_types = {
      markers = {
        text = function(line, level)
          return vim.fn.foldtext()
        end
      }
    }
<
```

2024-12-14 01:30 UTC, rhelder commented on doc/vimtex.txt
> +<
Sounds good to me! I just pushed the changes.

2024-12-14 14:43 UTC, lervag commented
Thanks!

2024-12-14 14:43 UTC, closed without merging

2024-12-14 18:19 UTC, rhelder commented
My pleasure! Thanks as always for your work.